<html>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
    <head>
        <meta charset="UTF-8">
        <title>Enderecos</title>
    </head>
    <body>
        <div>
            <h1>Enderecos</h1>
            <table>
                <tr>
                    <th>ID_ENDERECO</th>
                    <th>ID_CLIENTE</th>
                    <th>CEP</th>
                    <th>RUA</th>
                    <th>CIDADE</th>
                    <th>BAIRRO</th>
                    <th>ESTADO</th>
                    <th>NUMERO</th>
                    <th>COMPLEMENTO</th>
                    <th>REFERENCIA</th>
                </tr>
                <c:forEach var="endereco" items="${enderecosUsuario}">
                    <tr>
                        <td>"${endereco.id_Endereco}"</td>
                        <td>"${endereco.id_Cliente}"</td>
                        <td>"${endereco.cep}"</td>
                        <td>"${endereco.endereco_Rua}"</td>
                        <td>"${endereco.cidade}"</td>
                        <td>"${endereco.bairro}"</td>
                        <td>"${endereco.estado}"</td>
                        <td>"${endereco.numero}"</td>
                        <td>"${endereco.complemento}"</td>
                        <td>"${endereco.referencia}"</td>
                    </tr>
                </c:forEach>
            </table>
        </div>
    </body>
</html>